Update
Kaan9393/Webbshop pull request #84
Opened 2021-04-07 13:25 UTC by Kaan9393

2021-04-07 13:49 UTC, Chappi3 commented on Kladbutiken/Pages/CategoryCrud/Details.cshtml.cs
> +            //Category = await _context.Categories.FirstOrDefaultAsync(m => m.ID == id);
Ska finnas

2021-04-07 13:50 UTC, Chappi3 requested changes
Category måste finnas

2021-04-08 08:00 UTC, arkestal approved these changes

2021-04-08 08:11 UTC, Chappi3 approved these changes

2021-04-08 08:21 UTC, plurre88 approved these changes

2021-04-08 08:23 UTC, d0senb0den approved these changes

2021-04-08 08:31 UTC, merged