commit
Kaan9393/Webbshop pull request #88
Opened 2021-04-07 13:37 UTC by Rickard-Kujala

2021-04-07 14:00 UTC, Chappi3 requested changes

2021-04-07 14:00 UTC, Chappi3 commented on Kladbutiken/Pages/CategoryCrud/Create.cshtml.cs
> +            LoggedInAs = await UserCookieHandler.GetUserByCookie(userDetailsCookie);
bör ha med cart session och kolla om user cookien är null

2021-04-07 14:01 UTC, d0senb0den requested changes
Kollar ej om userDetailsCookie är null.
Skulle även returnera RedirectToPage("/login")

2021-04-08 07:52 UTC, Chappi3 approved these changes

2021-04-08 08:11 UTC, arkestal approved these changes

2021-04-08 08:12 UTC, plurre88 approved these changes

2021-04-08 08:21 UTC, d0senb0den approved these changes

2021-04-08 08:22 UTC, Kaan9393 approved these changes

2021-04-08 08:23 UTC, merged